module.exports={
    mode:"development",
    entry:[
        './src/index.js'
    ],
    module:{
        rules:[
            {
                test:/\.js$/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['@babel/preset-env'],
                        plugins:[['@babel/plugin-transform-react-jsx',{
                            pragma:'createElement'
                        }]]
                    }
                }
            },
            {
                test:/\.css$/,
                use:['style-loader','css-loader']
            }
        ]
    },
    optimization:{
        minimize:false
    }
}